# Generated by Django 4.2.9 on 2026-10-02 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=20, unique=True, verbose_name='预约编号')),
                ('handover_unit', models.CharField(max_length=100, verbose_name='移交单位')),
                ('goods_description', models.CharField(max_length=200, verbose_name='物资说明')),
                ('scheduled_start', models.DateTimeField(verbose_name='预约时间窗开始')),
                ('scheduled_end', models.DateTimeField(verbose_name='预约时间窗结束')),
                ('estimated_quantity', models.PositiveIntegerField(verbose_name='预估件数')),
                ('status', models.CharField(choices=[('pending', '待签到'), ('received', '已接收'), ('partial_received', '部分接收'), ('rejected', '已拒收'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reschedule_count', models.PositiveIntegerField(default=0, verbose_name='改期次数')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '到场预约',
                'verbose_name_plural': '到场预约',
                'db_table': 'ap_appointment',
                'ordering': ['scheduled_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(max_length=50, verbose_name='实际交接人姓名')),
                ('handler_id_card', models.CharField(blank=True, max_length=18, verbose_name='实际交接人证件号')),
                ('identity_matched', models.BooleanField(default=False, verbose_name='身份核对通过')),
                ('actual_quantity', models.PositiveIntegerField(verbose_name='实际件数')),
                ('decision', models.CharField(choices=[('accepted', '接收'), ('partial', '部分接收'), ('rejected', '拒收')], max_length=20, verbose_name='接收决定')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='接收件数')),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签到时间')),
                ('arrival_status', models.CharField(choices=[('on_time', '准时'), ('early', '提前到场'), ('late', '迟到')], max_length=20, verbose_name='到场状态')),
                ('remark', models.TextField(blank=True, verbose_name='现场备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='appointments.appointment', verbose_name='到场预约')),
                ('duty_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='值班员')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_check_ins', to='warehouse.goods', verbose_name='入库货物')),
            ],
            options={
                'verbose_name': '到场签到记录',
                'verbose_name_plural': '到场签到记录',
                'db_table': 'ap_check_in',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=18, verbose_name='证件号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='appointments.appointment', verbose_name='到场预约')),
            ],
            options={
                'verbose_name': '预约交接人员',
                'verbose_name_plural': '预约交接人员',
                'db_table': 'ap_appointment_handler',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', '创建预约'), ('rescheduled', '预约改期'), ('check_in', '签到接收'), ('duplicate_check_in', '重复签到'), ('cancelled', '取消预约')], max_length=20, verbose_name='事件类型')),
                ('detail', models.TextField(blank=True, verbose_name='轨迹描述')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appointments.appointment', verbose_name='到场预约')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '预约轨迹',
                'verbose_name_plural': '预约轨迹',
                'db_table': 'ap_appointment_event',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
