# Generated by Django 4.2.9 on 2026-10-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_no', models.CharField(max_length=20, unique=True, verbose_name='预约编号')),
                ('transfer_unit', models.CharField(max_length=100, verbose_name='移交单位')),
                ('expected_start', models.DateTimeField(verbose_name='预约开始时间')),
                ('expected_end', models.DateTimeField(verbose_name='预约结束时间')),
                ('expected_quantity', models.PositiveIntegerField(verbose_name='预估件数')),
                ('handover_person', models.CharField(max_length=50, verbose_name='交接人员')),
                ('handover_person_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('handover_person_id_card', models.CharField(blank=True, max_length=18, verbose_name='证件号码')),
                ('status', models.CharField(choices=[('pending', '待到场'), ('received', '已接收'), ('partial', '部分接收'), ('rejected', '已拒收'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '到场预约',
                'verbose_name_plural': '到场预约',
                'db_table': 'wh_appointment',
                'ordering': ['expected_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签到时间')),
                ('arrival_status', models.CharField(choices=[('early', '提前到场'), ('on_time', '准时到场'), ('late', '迟到')], max_length=20, verbose_name='到场状态')),
                ('actual_person', models.CharField(max_length=50, verbose_name='实际交接人')),
                ('actual_person_id_card', models.CharField(blank=True, max_length=18, verbose_name='证件号码')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='身份核验通过')),
                ('actual_quantity', models.PositiveIntegerField(verbose_name='实际件数')),
                ('decision', models.CharField(choices=[('receive', '接收'), ('partial', '部分接收'), ('reject', '拒收')], max_length=20, verbose_name='接收决定')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='实收件数')),
                ('discrepancy_note', models.TextField(blank=True, verbose_name='差异说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='warehouse.appointment', verbose_name='预约')),
                ('duty_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to=settings.AUTH_USER_MODEL, verbose_name='值班员')),
            ],
            options={
                'verbose_name': '签到接收记录',
                'verbose_name_plural': '签到接收记录',
                'db_table': 'wh_reception',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', '创建预约'), ('rescheduled', '预约改期'), ('check_in', '到场签到'), ('duplicate_check_in', '重复签到'), ('received', '接收'), ('partial_received', '部分接收'), ('rejected', '拒收'), ('cancelled', '取消预约')], max_length=30, verbose_name='事件类型')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='事件详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warehouse.appointment', verbose_name='预约')),
            ],
            options={
                'verbose_name': '预约轨迹',
                'verbose_name_plural': '预约轨迹',
                'db_table': 'wh_appointment_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stockin',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to='warehouse.appointment', verbose_name='来源预约'),
        ),
    ]
